name: Build and Push Docker images

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Docker image tags
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: woods245/ceg3120proj4
        tags: |
          latest
          ${{ github.ref }}
          ${{ env.VERSION }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

