name: Build and push Docker image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          docker.io/woods245/ceg3120proj4:${{ github.ref }}
          docker.io/woods245/ceg3120proj4:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate Docker image metadata
      uses: docker/metadata-action@v3
      with:
        images: docker.io/woods245/ceg3120proj4
      id: metadata

    - name: Publish Docker image metadata
      uses: docker/metadata-action@v3
      with:
        images: docker.io/woods245/ceg3120proj4
        metadata: |
          {
            "name": "ceg3120proj4",
            "tags": ${{ steps.metadata.outputs.tags }}
          }
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


