name: Build and Push Docker images

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate Docker image tags
      id: docker/metadata
      uses: docker/metadata-action@v3
      with:
        images: docker.io/woods245/ceg3120proj4

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ steps.docker/metadata.outputs.tags }}
          docker.io/woods245/ceg3120proj4::latest

