name: Docker Build and Publish
on:
  push:
    tags:
      - '*'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t woods245/ceg3120proj4:$GITHUB_REF .
    - name: Generate Metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: woods245/ceg3120proj4:$GITHUB_REF
        tags: |
          latest
          ${{ github.ref }}
          ${{ github.ref }}-{{ github.sha }}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: |
        docker push woods245/ceg3120proj4:${{ github.ref }}
        docker push woods245/ceg3120proj4:latest

